sudo: required
language: go

go:
  - 1.5.1
  - tip

services:
  - docker

before_install:
  - pip install --user codecov

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v -t ./...
  - export PATH=$PATH:$GOPATH/bin
  - chmod +x build
  - wget -O $GOPATH/bin/p4 http://ftp.perforce.com/pub/perforce/r15.2/bin.linux26x86_64/p4
  - chmod +x $GOPATH/bin/p4

script:
  - ./build

after_success:
  - codecov
