sudo: required
language: go

go:
  - 1.5.1
  - tip

services:
  - docker

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v -t ./...
  - export PATH=$PATH:$GOPATH/bin
  - chmod +x build

script:
  - ./build
