#!/bin/bash

set -e

bundle install

go build -x -o bin/in in/main.go
go build -x -o bin/out out/main.go
go build -x -o bin/check check/main.go

go test in/*
go test out/*
go test check/*

docker build --rm -t olhtbr/p4-resource .

bundle exec rake spec
