#!/bin/bash

set -e

bundle install

go build -x -o bin/in in/main.go
go build -x -o bin/out out/main.go
go build -x -o bin/check check/main.go

# Start local Perforce server for testing
docker run --name p4d -d -p 1666:1666 nikhilv/p4d

# Always stop the server
function cleanup {
  docker rm -v -f p4d
}
trap cleanup EXIT

ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --trace --compilers=2 --progress

docker build -t olhtbr/p4-resource .

bundle exec rake spec
